### ISSUE TITLE
Detect and set track for firmware if no track detected by firmware

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#1007]
For things to "just work", the app should add the track the user is at for RC/RCP/RCA if the firmware does not detect a track. Use the new 'setLiveTrack' command.

**Comment by stieg** [comment]
Be careful here.  RCP may not detect a track because it doesn't yet have GPS.  You must differentiate between it failing to detect because of lack of capability vs actual failure because no track is loaded.

**Comment by ryandoherty** [comment]
Yup, that would be part of the full requirements/spec 👍

**Comment by brentpicasso** [comment]
handled in new track auto-detection made available in 1.8.0
