### ISSUE TITLE
Pressing tab key doesn't move to next form field

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#1011]
In normal apps and webpage, pressing the Tab key will move your cursor to the next form field. This doesn't happen in our app, due to it being Kivy based. Need to figure out if this is possible.

**Comment by brentpicasso** [comment]
It is possible, but the tab stops need to be explicitly enabled.  See the
analog scaling grid for an example.

On Thu, Jun 9, 2016 at 12:49 PM, Ryan Doherty <notifications@github.com>
wrote:

> In normal apps and webpage, pressing the Tab key will move your cursor to
> the next form field. This doesn't happen in our app, due to it being Kivy
> based. Need to figure out if this is possible.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/autosportlabs/RaceCapture_App/issues/1011>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ADHbzTB4BfjC_GJYzvSJKkDIRZUQQNCrks5qKG4vgaJpZM4IyVnq>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*
