### ISSUE TITLE
Make GPS channel settings configurable. 

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1019]
While we have a simplified way of enabling / disabling various GPS related channels, we don't have a way to adjust other settings, like precision. 

Possibly provide the same gear icon that would pop up channel customization dialog that had a read-only channel name.

**Comment by brentpicasso** [comment]
Related https://github.com/autosportlabs/RaceCapture_App/issues/748

**Comment by stieg** [comment]
> we don't have a way to adjust other settings, like precision.

Not sure there is anything to fix here.  Firmware already prints the maximum amount of precision you will get from GPS because we use floats internally to hold lat/lon positions.  Perhaps you can describe the problem you hit and why this is the solution to it?
