### ISSUE TITLE
Pressing 'Esc' key when viewing a config modal returns app to home screen

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#1047]
(Observed in 1.6.0 Bluetooth config branch)
STR:
- Open Config/Setup screen
- Go to Wireless config
- Click on Advanced button
- Press Esc key
- See how main view changes to homepage: http://i.imgur.com/Jra1Doc.png

Expected behavior:
- Modal is dismissed, main view does not change.

**Comment by brentpicasso** [comment]
No longer reproduces; fixed in a previous build.
