### ISSUE TITLE
enable switch to convert from metric to imperial distance and speed units.

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1051]
Need the ability for the user to select between metric or imperial units in analysis views.

Can be a central option in analysis, or, on a chart by chart basis.  Leaning towards a central option.

**Comment by mumchristmas** [comment]
Some advice... That's right to handle the unit converting in the app side. But the RCP/RCT firmware is doing the same thing at the same time. So we get the raw OBD signal in metric, then turn into imperial by firmware, and turn back to metric by app... Quite disorderly, right?

**Comment by brentpicasso** [comment]
closing; #1288 will handle this issue.
