### ISSUE TITLE
RCPAPI message rx worker doesn't log exceptions properly

### ISSUE THREAD

**Issue by ddimensia** [autosportlabs/RaceCapture_App#1053]
If an exception occurs while processing messages in the rcpapi message_rx_worker a log message will be output like:

[WARNING] [RCPAPI      ] Message rx worker exception: {"ver::{"major":
2}} | <type 'exceptions.Exception'>

Instead of outputting the information in the exception the code is outputting the type 'Exception'.  In addition, non-printable and some whitespace/formatting characters in the received message can make the logged output difficult to read.

See PR #1050

**Comment by ryandoherty** [comment]
#1050 was merged, closing.
