### ISSUE TITLE
Add schema migration tool

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#1057]
Current candidates Alembic and SQLAlchemy Migrate.

Rough requirements:
- SQLite support
- Win/OSX/Linux/iOS/Android support (anything else? BeOS?)
- Migrate up/down (needed for development of migrations)
- Handle branching of code and migrations occurring in multiple branches. Probably means not use a simple schema revision number, but instead some more complex timestamp + table tracking what migrations have occurred. See Rails migrations for an example.

**Comment by brentpicasso** [comment]
chose sqlturk as lightweight embeddable option.
