### ISSUE TITLE
Make dashboard screen loading more responsive

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1060]
When initially loading the dashboard the app seems to hang while the screen is built. We need to make this feel more responsive for the user, even if the same amount of time is required to load the screen.

**Comment by ryandoherty** [comment]
I think this falls under performance work in https://github.com/autosportlabs/RaceCapture_App/issues/918, let's not use a bandaid solution of adding a spinner/loader. Profile it first and see how we can reduce load time.
