### ISSUE TITLE
Move datastore file initialization to inside datastore class

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#1061]
The AnalysisView should not handle checking if the datastore file exists, the DataStore class should be responsible for it. This would allow the DataStore to manage how it stores its data, external classes should not be looking for DataStore dependencies.

**Comment by brentpicasso** [comment]
this has since been refactored in a previous commit / release.  main.py calls a high level function in datastore and the datastore now handles the creation of the DB if necessary.
