### ISSUE TITLE
Automatically name sessions with track name

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#1070]
Currently sessions recorded by the app are the timestamp of when recording started. The app should autoname the session with the nearest track it finds. If GPS is not available, it should use a timestamp, then when GPS has a lock, rename the session (while in dashboard mode, not afterwards)

**Comment by brentpicasso** [comment]
It could also be added to the dashboard preferences screen, too - maybe.

**Comment by brentpicasso** [comment]
Implemented in previous release.
