### ISSUE TITLE
Hide firmware update menu item if RC device is connected over wifi

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#1077]

**Comment by ddimensia** [comment]
Seems like the best way to do this might be to add a method to the RcpApi class that determines if a feature is supported.  In this case the feature would be firmware update.  The RcpApi could either defer that to the comms object or return a value based on the type of the comms object.  This would also mean the current FIRMWARE_UPDATABLE property in configview.py should probably be removed in preference of the new RcpApi method.

Neither the SystemSettings nor RcpConfig classes seem appropriate.

**Comment by brentpicasso** [comment]
This is a function of the interface - where firmware updates are only supported over USB - so having it served up via RcpApi through the specific connection as a type of feature flag or boolean class property seems appropriate.
