### ISSUE TITLE
msvcr100.dll missing error on Windows 7 and 10

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#1088]
On version 1.6.0 on Windows 7 and 10, RaceCapture app fails to start due to a missing dll file named 'msvcr100.dll'

**Comment by ryandoherty** [comment]
FWIW the app loads on Win7 32 bit in a VM. On a very clean, native Windows 10 Pro 64 bit it fails to launch.

**Comment by ryandoherty** [comment]
Possibly related? Python 3 Kivy info talks about this dll https://github.com/kivy/kivy/wiki/Building-Portable-Package

**Comment by brentpicasso** [comment]
I believe this is due to a bad installer. 1.8.0 has an additional installer switch that does a better job to include libs.

**Comment by brentpicasso** [comment]
https://msdn.microsoft.com/en-us/library/ms235299.aspx is the package needed to work around this issue.

Apparently if these DLLs are included in the directory where the executable resides it will also resolve the issue.

**Comment by brentpicasso** [comment]
Discussion / backstory here: https://forum.autosportlabs.com/viewtopic.php?t=5117&sid=0c2c4c1e593ad7c671430a79e36ddca0
