### ISSUE TITLE
SessionRecorder: enhance name and timestamp in saved sessions

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1092]
Name:
- Auto-generate name based on detected track, if possible. 

Timestamp:
have a scheme that's easier to visually recognize when a session occurred.  Riffing off what you see in other apps, like facebook when it shows when something occurred, like a comment. 

Ideas (not all have to be implemented)
- If it happened within an hour, show the session time as (XX minutes ago)
- If it happened today, show session time as (Today at HH:MM:SS)
- If it happened within a week, show session time as (XX days ago)
- If it happened beyond that, just show the date / time.

**Comment by ryandoherty** [comment]
+1, I had this in my todo list later. One big note: timestamps differ per locale, so we need the timestamps we generate use locale-dependent formatting: MM/DD/YY - US, DD/MM/YY - UK, Germany, etc.

**Comment by ryandoherty** [comment]
`strftime` does have locale formatted strings, but not in any customizable form though: https://docs.python.org/2/library/time.html#time.strftime
