### ISSUE TITLE
SessionRecorder: performance testing

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1094]
Since SessionRecorder is doing the SQL inserts in the UI thread, we should do some performance testing to see what conditions may cause the app to visually lag.

**Comment by ryandoherty** [comment]
+1 on moving the db stuff to a separate thread since sqlite is file-based, I'm worried that any small I/O glitch or blocking will block the UI completely

**Comment by brentpicasso** [comment]
Observed evidence of various slowdowns of UI responsiveness, based on performance of disk storage.  Performance returned to normal when session recording was turned off. 

Recommend queueing samples to a background thread to keep UI responsive.
