### ISSUE TITLE
Cancel X in pit stop timer popup does not hide pit stop timer

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#1099]
Had a user report this from the field, we should investigate and attempt to reproduce. Was on an older, slower tablet, could be hardware/performance related.

**Comment by brentpicasso** [comment]
Please try to get tablet  make / model if possible to help diagnose.

**Comment by brentpicasso** [comment]
Cannot repro this on our recommended tablets. Low end recommended tablet (Fire) properly handles the dismiss.
