### ISSUE TITLE
Add method to rcpapi object to get multiple configs/info in 1 call

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#1110]
Sometimes parts of the RC app need to query for multiple pieces of information before they can continue, a way to call multiple getXXX() calls in 1 call and get a return value that combines them all would be really handy.

Also, we may want to look into if Python has any Promises libraries and wrap the API in it. Would make these types of things much easier.

**Comment by brentpicasso** [comment]
this is already handled in get sequence, with existing wrappers in rcpapi. This should meet the requirements here.
