### ISSUE TITLE
When flashing firmware, session recorder repeatedly attempts to stop

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1111]
STR:

update firmware. 
Observe the following in log

[INFO   ] [FirmwareUpdateView] Disabling RaceCapture Communcications
[INFO   ] [TelemetryManager] on_data_connected: False
[INFO   ] [SessionRecorder] stopping session
[INFO   ] [SessionRecorder] stopping session
[INFO   ] [SessionRecorder] stopping session
[INFO   ] [FwUpdater   ] Searching for an active bootloader
[INFO   ] [SessionRecorder] stopping session
[INFO   ] [FwUpdater   ] Found bootloader ver: 0.3.0 on: /dev/ttyACM0
[INFO   ] [SessionRecorder] stopping session
[INFO   ] [FwUpdater   ] Updating firmware...
[INFO   ] [SessionRecorder] stopping session
[INFO   ] [SessionRecorder] stopping session

**Comment by ryandoherty** [comment]
Tested, does not happen anymore.
