### ISSUE TITLE
Stop Telemetry Stream When Configuring, Restart When Complete

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture_App#1116]
Currently in our app we leave the telemetry stream running when a user tries to configure the system.  While this does work, it creates a poor user experience since the user must wait for queued telemetry messages to send before it can receive the replies to the command.

To improve upon this we should stop the telemetry stream, send and receive commands, then start the telemetry stream.  This should make programming operations much quicker.  And since a user is likely not on track while programming the device, it should in no way impact their experience.

**Comment by brentpicasso** [comment]
This issue replaced by #1190
