### ISSUE TITLE
Slow discovery of RC on Android when connected to RC's AP

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#1151]
Takes > 10s for a fresh, clean install of the RC app on Android to discover RC when connected to RC's AP. Seems a lot faster when RC is in client mode.

**Comment by brentpicasso** [comment]
I will test this again

**Comment by brentpicasso** [comment]
I'm seeing this too when connected to RC's AP.  

Will check client mode (common AP and phone hot spot)

I/python  (17746): [INFO              ] [RCPAPI      ] auto_detect_worker starting
I/python  (17746): [INFO              ] [SocketConnection] listening for RC wifi...
I/python  (17746): [INFO              ] [SocketConnection] found no RC wifi (timeout listening for UDP beacon)
I/python  (17746): [INFO              ] [SocketConnection] listening for RC wifi...
I/python  (17746): [INFO              ] [SocketConnection] found no RC wifi (timeout listening for UDP beacon)
I/python  (17746): [INFO              ] [SocketConnection] listening for RC wifi...
I/python  (17746): [INFO              ] [RaceCaptureApp] Current Tracks Loaded
I/python  (17746): [INFO              ] [SocketConnection] found no RC wifi (timeout listening for UDP beacon)
I/python  (17746): [INFO              ] [SocketConnection] listening for RC wifi...
I/python  (17746): [INFO              ] [Android     ] Must go into sleep mode, check the app
I/python  (17746): [INFO              ] [Android     ] App paused, now wait for resume.
I/python  (17746): [INFO              ] [SocketConnection] found no RC wifi (timeout listening for UDP beacon)
I/python  (17746): [INFO              ] [Android     ] Android has resumed, resume the app.
I/python  (17746): [INFO              ] [Android     ] App resume completed.
I/python  (17746): [INFO              ] [SocketConnection] listening for RC wifi...
I/python  (17746): [INFO              ] [SocketConnection] found no RC wifi (timeout listening for UDP beacon)
I/python  (17746): [INFO              ] [SocketConnection] listening for RC wifi...
I/python  (17746): [INFO              ] [SocketConnection] found no RC wifi (timeout listening for UDP beacon)
I/python  (17746): [INFO              ] [SocketConnection] listening for RC wifi...
I/python  (17746): [INFO              ] [SocketConnection] got UDP data {"beacon":{"name":"RCT","port":7223,"serial":"360026000157335239383620","ip":["192.168.4.1"]}}
I/python  (17746): [INFO              ] [SocketComm  ] connection process start

**Comment by brentpicasso** [comment]
Nearly instantaneous when connecting to phone in hotspot mode:
I/python  (20325): [INFO              ] [AndroidComms] close
I/python  (20325): [INFO              ] [Racecaptureapp] RC connection type changed to WiFi, restarting comms
I/python  (20325): [INFO              ] [RCPAPI      ] msg_rx_worker exiting
I/python  (20325): [INFO              ] [RCPAPI      ] cmd_sequence_worker exiting
I/python  (20325): [INFO              ] [AndroidComms] close
I/python  (20325): [INFO              ] [RacecaptureApp] initializing rc comms with, conn type: WiFi
I/python  (20325): [INFO              ] [SocketComm  ] init
I/python  (20325): [INFO              ] [RCPAPI      ] msg_rx_worker starting
I/python  (20325): [INFO              ] [RCPAPI      ] cmd_sequence_worker starting
I/python  (20325): [INFO              ] [RCPAPI      ] auto_detect_worker starting
I/python  (20325): [INFO              ] [SocketConnection] listening for RC wifi...
I/python  (20325): [INFO              ] [SocketConnection] got UDP data {"beacon":{"name":"RCT","port":7223,"serial":"360026000157335239383620","ip":["192.168.43.63","192.168.4.1"]}}
I/python  (20325): [INFO              ] [SocketComm  ] connection process starting

**Comment by brentpicasso** [comment]
I vote for punting this until 1.7.1.  Might be unrelated to android.

**Comment by brentpicasso** [comment]
Nope, I tested on Desktop and UDP discovery happened instantly.

**Comment by ryandoherty** [comment]
I can confirm desktop is slightly faster.

I did a Wireshark analysis when connected to RC's AP, for 10s I did not see any UDP packets from RC. Wonder if something is different about AP mode in firmware or the wifi chip? @stieg any thoughts/ideas?

**Comment by stieg** [comment]
Was the client settings on the WiFi correct (if it was enabled to begin with).  WiFi client / host settings happen before data settings so if client is failing to connect for any reason it may have implications.  Do you have any log files from the unit?  How about configuration information.  If you see the periodic blue flashing it means the beacon is going out.  My guess is that it may be stuck trying to setup client config and failing, and then going to beacon.  That takes about 10 seconds usually.

**Comment by ryandoherty** [comment]
Client mode is off and blank. Will test and upload configs and logs.

**Comment by ryandoherty** [comment]
Config file. Ran desktop app connected to RC with AP mode on, didn't see anything in the logs other than the app requesting status and log.

[ap mode discovery bug.txt](https://github.com/autosportlabs/RaceCapture_App/files/430997/ap.mode.discovery.bug.txt)

**Comment by ryandoherty** [comment]
If I have RC connect to my wifi network and do a Wireshark sniff, I see UDP beacon packets from RC.

**Comment by stieg** [comment]
The file provided has no Wireless config in it.

**Comment by ryandoherty** [comment]
Oops: 
[save wifi cfg.txt](https://github.com/autosportlabs/RaceCapture_App/files/431183/save.wifi.cfg.txt)

**Comment by stieg** [comment]
So in that config your client mode is enabled.  Try disabling that and see if that helps

**Comment by ryandoherty** [comment]
When client mode is disabled I see this behavior, the configuration is from a later test when client mode was enabled.

**Comment by brentpicasso** [comment]
tried to repro this on laptop. Disabled client mode on RCT, connected to RCTs AP with laptop's wifi. 

Discovered and connected in less than 2 seconds.

**Comment by brentpicasso** [comment]
Tried on android again, fresh install, phone connected to RCTs AP. RCT client disabled.  Connected in about 5 seconds. 

Tried a 2nd time; connected within 5 seconds again.

**Comment by brentpicasso** [comment]
Still think this is an issue to resolve?

**Comment by stieg** [comment]
Close it as resolved.  Can reopen it if still an issue.  Looks like it was
resolved to me
