### ISSUE TITLE
flag dependent config screens don't correctly refresh after config is loaded

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1158]
Specifically, wireless config screen. 

If you navigate to the screen, it loads a default view with all options enabled. Once the config is read,  sections are not refreshed to reflect actual capabilities for MK2 and MK1.  RCT looks correct.

If you navigate to the screen after the config is loaded, incorrect options are shown.
MK2: 
No cellular or BT configuration shown
MK1:
Screen is simply blank

**Comment by ryandoherty** [comment]
What version(s) of firmware for mk1 & mk2?

**Comment by brentpicasso** [comment]
MK1 2.8.7 / MK2 top of 2.10.0
