### ISSUE TITLE
delimit all messages with \r\n

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1165]
Issue logged against 1.7.1; see previously closed PR #1153 

This is because we treat all commands as serial line commands. Thus
we should use proper serial line delimeters to delimit the end of a
command.

As an added bonus this helps us work around a shortcoming in the ESP8266
chip (IPD doesn't terminate lines with \r\n). This allows our serial
library to always read and handle the line appropriately.

**Comment by ryandoherty** [comment]
Merged https://github.com/autosportlabs/RaceCapture_App/commit/4cbf9cf4b4323a317938a26501e26b75b337eefe
