### ISSUE TITLE
Send only what changed Wifi Config Wise

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture_App#1197]
Followup bug from issue https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/848.  Assume a user changes only the AP wifi settings, the app will still send the following JSON when configuring the Wifi:

```json
{"setWifiCfg":{"active":true,"ap":{"active":true,"encryption":"none","password":"","ssid":"RaceCapture 34330313020","channel":8},"client":{"active":true,"password":"<REDACTED>","ssid":"LAN Downunder"}}}
```

This is incorrect because the user made no changes to the client wifi settings.  This will cause un-altered settings to be applied to our client, which will unnecessarily disrupt the client wifi.  If instead you sent the following:

```json
{"setWifiCfg":{"active":true,"ap":{"active":true,"encryption":"none","password":"","ssid":"RaceCapture 34330313020","channel":8}}}
```

Then there would be no client disruption since no client settings were included in the command.  The same applies in reverse.  In short, only send what changes actually need to be applied, otherwise unnecessary disruption may occur.

**Comment by stieg** [comment]
Now that #848 has some additional code to help deal with the verbose configuration details, this may not need to be solved.  In general it's is best to provide only what is needed.  But the device should be smart too.  Oh tradeoffs

**Comment by brentpicasso** [comment]
Closing now that we have the 'apply' flag in 2.10.0 firmware, handled by a different solution.
