### ISSUE TITLE
Consider having thea App warn users about changing WiFi settings when connecting using Wifi with device

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture_App#1202]
Doing so could cause a disruption and failure when writing  a config since the Wifi will apply the changes as soon as it gets them.  Currently I will only apply new changes if the configuration changed and I wait 1 second to do this so as to give the reply message time to send.

**Comment by brentpicasso** [comment]
Leverage the firmware's 'apply' flag when connected over wifi to apply changes upon power-cycle.

**Comment by brentpicasso** [comment]
Use a helpPopup to provide this advisory message for a quick / effective solution.
