### ISSUE TITLE
Connection drops if CPU is excessively loaded

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1210]
Noticed that the current connection will drop if the CPU is excessively loaded. Observed with WiFi SocketConnection. 

maybe extend timeout?

**Comment by ryandoherty** [comment]
I'm wary of extending timeouts, they may overlap with timeouts that detect if RC has actually disconnected. We should at least investigate if we can somehow prevent the main thread from stealing too much time from other threads (not sure if that's even possible in Python). 

Sadly we can't do any event-driven type of system or even actually detect a true disconnect in Python from my research.

**Comment by ryandoherty** [comment]
This may help: http://stackoverflow.com/a/21802953/956

**Comment by ryandoherty** [comment]
And as a last resort Brent suggested we use asyncore. We use it in the telemetry connection and it's never dropped connections with the CPU is overloaded. It's a pita library to use, whomever uses it, follow the setup in the telemetry code, you can probably copy/pasta it.
