### ISSUE TITLE
Analog Sensors screen Rc App 1.7.4

### ISSUE THREAD

**Issue by cdoxp800** [autosportlabs/RaceCapture_App#1216]
On the Rc App 1.7.4 the Analog Sensors screen is all crammed together rendering it useless on the Galaxy S5. Now on the Kindel Fire Tablet is looks fine.

![22828](https://cloud.githubusercontent.com/assets/22123069/18413757/6b4288d8-7778-11e6-937e-8541393ce221.png)

**Comment by brentpicasso** [comment]
thanks for the report.  We got this covered in #1180 , so will mark this as a duplicate.
