### ISSUE TITLE
make autogenerated session name more concise

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1256]
Currently it makes a <date> <time> format, which is very long.

Suggested format:

<date> - <ordinal>

like:

1/1/2001 - 1
1/1/2001 - 2

This will fit nicely into various areas of the analysis view.

**Comment by ryandoherty** [comment]
Since our app is used internationally, I think in addition to this we need a preference in app to allow users to choose their date format, which is then used in the session name. Or somehow detect their locale's date format.
