### ISSUE TITLE
Have exit app button in left popout menu (for desktop only)

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1257]
Include an exit menu option for the left menu options drawer, available on desktop only. 

Suggested fontawesome icon: fa-eject [&#xf052;]

Not a lot of good matches for icons, open to suggestions

**Comment by ddimensia** [comment]
I was thinking of using the fa power-off icon but eject would work also.

Is there a reason not to allow it show it on mobile?  The obvious concern I would have is that it could be accidentally hit via a touch screen.  My plan was to place it at the bottom of the main menu so there was space between it and the System Status item. 

Example:
<img width="1027" alt="screen shot 2016-09-20 at 11 11 00 pm" src="https://cloud.githubusercontent.com/assets/1389554/18700153/8e605e0c-7f8a-11e6-81e2-7a0053ffe153.png">

**Comment by ddimensia** [comment]
I have the changes made up against the 1.7.5 branch.  There's no 1.7.6 branch created yet so I can't send up a PR.  Currently, I have it written so that it removes the 'Exit' menu item if the platform is IOS or Android.  That bit of code could easily be removed if it was determined to be acceptable on any platform.

**Comment by brentpicasso** [comment]
r/1.7.6 branch is up now.  I missed seeing the power button; I like it. 

No reason to not show it on all platforms, actually!

**Comment by ddimensia** [comment]
Still don't see a r/1.7.6 branch, did you push to origin/github?

**Comment by brentpicasso** [comment]
Ok, just pushed!

**Comment by brentpicasso** [comment]
Thanks @ddimensia  for the nice enhancement!
