### ISSUE TITLE
iOS app does not stay on (phone will sleep / display will time out)

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1328]
Our app has a flag to prevent the phone from sleeping / display turning off, but apparently it does not seem to work with iOS.  

Also, report has been made that app will lose it's RC data connection and/or freeze when coming out of sleep, requiring a phone restart. This needs to be reproduced.

**Comment by mattlqx** [comment]
I learned this while on track. :(

**Comment by brentpicasso** [comment]
Fixed in 1.12.0, one liner in iOS main()
