### ISSUE TITLE
[export] unable to access data exports on iOS

### ISSUE THREAD

**Issue by mattlqx** [autosportlabs/RaceCapture_App#1337]
Using the export option on iOS, exports to the app chroot, but I'm unable to access that data either through iTunes documents selection or iExplorer, the Race Capture app shows up for neither.

Alternative methods for exporting would help here. At minimum, through email. But more advanced implementations like exporting to iCloud Drive would be appreciated.

**Comment by brentpicasso** [comment]
Enabled App file sharing access via info pList for iOS app, per this guide: 
https://stackoverflow.com/questions/6029916/how-to-enable-file-sharing-for-my-app

Fixed in 1.12.0
