### ISSUE TITLE
Allow app to flip 180degrees

### ISSUE THREAD

**Issue by zero-below** [autosportlabs/RaceCapture_App#1340]
For cable routing, it's sometimes nice to flip the tablet. For example, the Nvidia shield routes cables out the left in the default layout. To use the tablet as a dashboard, they would be better out the right, which would need a 180degree flip.

**Comment by brentpicasso** [comment]
Thanks for reporting the issue!

This is a duplicate of https://github.com/autosportlabs/RaceCapture_App/issues/436
