### ISSUE TITLE
Serial comms should ignore /dev/ttyAMA0 on Raspbian

### ISSUE THREAD

**Issue by ddimensia** [autosportlabs/RaceCapture_App#1389]
On Raspbian, /dev/ttyAMA0 is the device for the bluetooth controller.  If the app attempts to communicate with this device it hangs the bluetooth stack until the device is rebooted.

**Comment by brentpicasso** [comment]
do you know if connecting to RCP over minicom using ttyAMA0 works successfully? That would help us understand if there's a problem with the app (via pyserial) or if there's a problem with the RPi  BT stack.
