### ISSUE TITLE
Invalid json on Serial connections causes failure to reattempt connection

### ISSUE THREAD

**Issue by ddimensia** [autosportlabs/RaceCapture_App#1390]
When connecting to a serial port (via bluetooth) on more than one occasion the app would display an error regarding the firmware version, displayed as 0.0.0.0, not being compatible with the app.  When this happens there is no attempt to re-establish a working connection.

In the cases that I've seen this occur there is also an error message in the logs related to an invalid json message.  It seems that the message handler should simply drop invalid json messages and not attempt to interpret the results of the partial deserialization.

**Comment by brentpicasso** [comment]
referenced commit should catch this issue. re-open if you still see it.
