### ISSUE TITLE
SessionRecorder dropping samples in RaceCapture under linux.

### ISSUE THREAD

**Issue by RodADavison** [autosportlabs/RaceCapture_App#1481]
I'm getting long streams of these messages:
[WARNING] [SessionRecorder] dropping sample; queue full
[WARNING] [SessionRecorder] dropping sample; queue full
[INFO   ] [SessionRecorder] queue backlog: 500

A little digging and some profiling reveals that a sqlite3.commit call in DataStore:insert_sample is taking a really long time.

I experimented with a couple of solutions: 
- first was to have the SessionRecorder:on_sample call, peek at the qsize() and combine samples when the consumer seemed to falling behind.  This stabilized things and reduced the sample rate to about 40-50ms (20-25Hz) which (correct me if I'm wrong) should be fast enough.
- second I reduced the frequency of the commit calls in DataStore:insert_sample so that it only commits one time in 50 -- this works out to about one commit every second.  (This should probably use a timer, not a counter). No data seemed to get lost with this approach.  With this my queue backlog never exceeds 1.  Although, there is an exception handler there that could rollback to the previous commit ... not sure when this might happen.
- I've also reduced my queue size from 500 to 20 (partly for debugging), but I think its better to have a smaller queue so that when things lag there is not a big backlog of events to deal with.
- the other thing to consider since (at least with my desk testing) many consecutive samples are the same except for the utc and interval values, avoid writing otherwise identical samples into the database.  This may not be very useful in real-life with car vibration etc.
#1399 
If you think this or some of this would be a valuable contribution, after a little cleanup, I could try to figure out how to create a pull request for these changes.

**Comment by brentpicasso** [comment]
Thanks, Rodney - this is good stuff, and we've been thinking about this issue as well when seeing the session recorder running on slower filesystems like the RPi. 

I think all of your suggestions seem reasonable, save for the last about dropping identical samples - we should still log those to confirm the sample entry. But I don't get the sense that this part is super important. 

I assume that the 'insert once per second' approach that you're batching up the inserts into one bigger batched transaction?

Would wecome a pull request against this. Thanks!

**Comment by RodADavison** [comment]
Yup, not hung up on removing identical samples.
The sql inserts would still take place at the high frequency.  The commit ... which allows other clients sharing the database to see the inserts ... would only take place every second.  sql takes care of the batching.  This would be problematic, if for example the UI was use the database for getting updated.  I don't actually know if there are any other clients for the database.  If there are time sensitive clients using the database 1 per second may be too slow.
I'll try to figure out how to correctly use github.  Standby.
Please, call me Rod.
