### ISSUE TITLE
Bluetooth takes a long time to reconnect

### ISSUE THREAD

**Issue by RodADavison** [autosportlabs/RaceCapture_App#1496]
I have 9 bluetooth devices that my phone is paired with ... I know it sounds like a lot ... but I use them all.  If I lose connection with with RCP and it doesn't catch it again on the first retry, it runs through all 8 of my other devices before it gets back to the RCP.  I haven't timed it, but feels like a minute or more.

I'd like to see it retry the previous connection again between each other paired device.  Eg.
[ previous_device, bt1, previous_device, bt2, previous_device, bt3 .... ]

If you think would be an improvement, I don't mind making the change, but it might not be an improvement for someone who is trying to connect to multiple RCPs.

**Comment by brentpicasso** [comment]
Hi - Note that the RaceCapture app is designed to first try the last successful connection. If it fails to connect to that, *then* it rolls through the complete list.  Please try and verify that first and see if that replicates for you. Thanks!

**Comment by RodADavison** [comment]
Yes.  What you describe is the current behaviour.  However, after a disconnect, it seems to take the RCP a few seconds (maybe 10 or so) to recognize that its been disconnected and go back into the "waiting for a connection state".  At this point (sometimes) the app has already tried and given up on the last successful device and has moved onto the other 8 devices.  Then I have to wait for it to cycle back to the beginning of that list before it connects.

**Comment by brentpicasso** [comment]
Did you simulate this with a quick power cycle of RCP, or some other technique to interrupt the connection?

**Comment by RodADavison** [comment]
From my phone - I run the app.  It connects and runs.  I exit the app.  If I start the app immediately it seems to connect fine.  If I wait a couple of minutes before I start the app it seems to connect on the first try too.
If I wait about 5 seconds after exiting it seems to be problematic.  The app tries the connect to the RCP but then moves on to the next BT device in my list.  The next time through the list,  about a minute later, it connects fine.

**Comment by brentpicasso** [comment]
Thanks. I think what you propose is a fine idea. It's a critical area of the system, so I suggest minimizing the footprint of the change. I think you will anyway, but it's worth mentioning. Thanks!
