### ISSUE TITLE
need to make the bluetooth password and device name configurable

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#551]
Limit this to 2.9.0 firmware and above.

**Comment by ryandoherty** [comment]
Some changes due to firmware/hardware limitations and security reasons:

The app will only change the passcode if a new passcode is entered into the configuration. It will not be shown to the user after RCP is disconnected. 

The reasons for this are:

* RCP cannot read configuration from the BT module
* Renaming the BT module on every power up would cause it to unpair from paired tablets/phones
* Showing the passcode and allowing it to be read from RCP's config is a security vulnerability.

**Comment by brentpicasso** [comment]
seems legit!
