### ISSUE TITLE
Docker Image for Install?

### ISSUE THREAD

**Issue by imhoffj** [autosportlabs/RaceCapture_App#747]

**Comment by brentpicasso** [comment]
Justin, did you get it working? I had some ideas for a Linux install if you
were stuck.

-Brent

On Mon, Nov 30, 2015 at 8:58 PM, Justin Imhoff <notifications@github.com>
wrote:

> Closed #747 <https://github.com/autosportlabs/RaceCapture_App/issues/747>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture_App/issues/747#event-478548579>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by ryandoherty** [comment]
FWIW we do have a Vagrant file for just this: https://github.com/autosportlabs/RaceCapture_App/blob/master/Vagrantfile

**Comment by imhoffj** [comment]
Thank for the Vagrant file and I really appreciate all the help! I will keep you updated on the progress for the environment setup.

**Comment by DavidMoeremans** [comment]
It took me also a few tries to setup the dev environment.
For me which was the main culprit, was the correct version of Cython
(0.21.2) which was needed to build the patched Kivy.

**Comment by RowanH** [comment]
@DavidMoeremans any chance you could share how your build script - not a python guy (ruby guy) and got myself round in circles trying to get kivy built.

**Comment by imhoffj** [comment]
For Linux I was finally successful on Ubuntu 15. This is what I had to do on a clean image:
1) Download the patched kivy repo
2) install pip in linux
3) install cython using pip
4) install py-game using pip
5) created the virtual environment
6) download and expand RaceCapture into _ve
7) installed the requirements
8) install asl_f4_loader
9) python main.py

I tired setup on mac, but way to many issues with latest version and py-game / 64 support. Tried on Windows 10 and was further, but still running into environment issues and clashing. Finally a clean linux build and was good to go. Python is also new to me, but will be a good challenge and the good part is how many OS the compiled app works under. I really came down to installing a module at a time and figuring out the errors. There is far more support for this setup using stackoverflow with linux then anything else.
