### ISSUE TITLE
Automagically set min/max values for known sensors

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#780]
It's very common for users to calibrate analog sensors correctly, but forget to set the min/max values. If they select a known channel name, we should auto-change the min/max values to good defaults.

Another option is to show the min/max values in the main analog edit section, instead of in the advanced/config popup.

**Comment by stieg** [comment]
Would be nice if the app somehow alerted you to say "Hey... fill these in" instead of guessing since these values can and do differ.

**Comment by ryandoherty** [comment]
It could do that, if they were shown in the main edit pane. Automagically selecting them is good too, it would work for 80-90% of users.

**Comment by brentpicasso** [comment]
Related issue: https://github.com/autosportlabs/RaceCapture_App/issues/772

The easy and simple approach would be to automatically expand the min/max ranges as necessary upon every datalog import.

**Comment by ryandoherty** [comment]
Not really, as the min/max values are used in the dashboard and are sent to RCL. The values should be fixed at the root cause, not later on after bad data has been sent and saved in various places.

**Comment by brentpicasso** [comment]
Ah, I had my mind on analysis / datastore.

The analog channel configuration is the center of most of this. the calibration map or the mapping formula could set some defaults, especially if  there's a wizard for calibrating a sensor (like a throttle position sensor).

We will also have a browseable list of sensor calibrations, similar to what we have for selecting race tracks of what we will have for CAN presets.  Once a pre-configured sensor is selected, it could also set min/max values.

**Comment by ryandoherty** [comment]
We do allow users to select the channel name when setting up an analog channel, we could show the min/max values near the name so it's apparent what they will be.

We also could take the min and max values for a mapped sensor and use those, since by default RCP won't ever calculate values outside that range.

I also agree changing meta values on import or after is needed too, for various reasons.

**Comment by ryandoherty** [comment]
FWIW RCL does have min/max values for all known channels and will use them if no min/max values are sent from RCP.

**Comment by brentpicasso** [comment]
As it turns out, when a user selects a channel preset (e.g. oil pressure) a proposed min/max/precision/units is auto-selected from the system channels.  It's kind of like a pre-set. So I think that fulfills this issue.  This is consistent on any channel selection drop-down.

Closing for now, pls re-open if otherwise.
