### ISSUE TITLE
Sensor calibration (Throttle position, fuel level..)

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#784]
Provide a tool to calibrate a sensor min / max values. 

Step the user through a min range, (poll analog channel) then a max range, (poll analog channel) then set the calibration map accordingly with the results.

**Comment by sab0276** [comment]
I would add an optional mid level as well (or more) just in case the calibration isn't exactly linear.

**Comment by brentpicasso** [comment]
duplicate of #475
