### ISSUE TITLE
Prod sentry errors are reported as 'dev'

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#810]
We have 0 production errors in Sentry, but some errors for our 'dev' app are > 1k errors reported. Seems like the production app is sending errors as dev.

**Comment by brentpicasso** [comment]
I think this means we might be using the wrong sentry.cfg file when building our APKs? Will check.

**Comment by brentpicasso** [comment]
Fixed to use the correct DSN for prod. will show up in 1.4.2
