### ISSUE TITLE
Instruct user to save current config before updating firmware

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#818]
before updating firmware, app should pop up a message instructing users to save their current config

**Comment by stieg** [comment]
Why not just have the app do it automatically as part of the upgrade process?  Perhaps just save it to a temp file to write back into RCP after the upgrade?  So the process would go:

* Download config to a temp file
* Upgrade firmware
* Upon successful upgrade, write config back.

That way it happens transparently.  Bonus points if it doesn't mess with the config UI screen.  Of course... not sure how complicated of a task that might be.

**Comment by brentpicasso** [comment]
Yes, this will be covered in #817 .   The configuration infrastructure also need to be worked over to handle multiple different devices (RCP, RC, etc),  #817 can get folded in to that effort in one shot.

This is just a quick PSA in the meantime, since we have nothing at the moment.

**Comment by stieg** [comment]
Got it.  Makes sense.
