### ISSUE TITLE
Data type feature request for app + server

### ISSUE THREAD

**Issue by zkdzegede** [autosportlabs/RaceCapture_App#838]
Not sure where to request features, so let me know if i should move this.

It would be nice to have the ability to set a data point with units of let's say "boolean" (for more extendable use), or maybe just the keyword "PitFlag" (for specific use) that would indicate the special data point (like the battery gauge).

Then on the web display it would show up as a LED gauge, with accompanying sound?

I'm thhinking of making a pit entry indication switch on my handle bars, and it would be nice to have that visual indication easy to see while my mechanic is showing my timeboard/clocking my lap time from the pit/other prep he may be doing.  Right now he'd have to watch a number value or graph line go high.

**Comment by zkdzegede** [comment]
FYI: I ride on a  2km length track and the pit lane is not long enough or far enough from the course for him to know well in advance that i'm pitting.

**Comment by brentpicasso** [comment]
So this is like a switch the rider would press or flip, which would cause
something to be noticed by the pit crew?

You can likely achieve that using a GPIO input and a Lua script to create a
virtual channel. This is how extended, highly specific features can be
created for users without having to bake it into the main firmware.

Many examples here:
https://autosportlabs.net/RaceCapturePro_Lua_Scripting_Examples

-Brent

On Fri, Jan 22, 2016 at 3:52 AM, zkdzegede <notifications@github.com> wrote:

> FYI: I ride on a 2km length track and the pit lane is not long enough or
> far enough from the course for him to know well in advance that i'm pitting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture_App/issues/838#issuecomment-173897813>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by zkdzegede** [comment]
I understand the virtual channel part.

My request is about the racecapture.com side in terms of handling the virtual channel I want to create, not firmware side.  I want a data type that will automatically show up like the image below (gpio switch type data)

Or is there already a way to do this?

![unspecified-3](https://cloud.githubusercontent.com/assets/2668400/12572665/99b17458-c432-11e5-8521-0fce2527588d.png)

**Comment by brentpicasso** [comment]
Got it. So, it sounds like you want to be able to select a type of gauge to
pair up with a certain data channel, correct?

-Brent

On Mon, Jan 25, 2016 at 8:42 PM, zkdzegede <notifications@github.com> wrote:

> I understand the virtual channel part.
>
> My request is about the racecapture.com side in terms of handling the
> virtual channel I want to create, not firmware side. I want a data type
> that will automatically show up like the image below (gpio switch type data)
>
> Or is there already a way to do this?
>
> [image: unspecified-3]
> <https://cloud.githubusercontent.com/assets/2668400/12572665/99b17458-c432-11e5-8521-0fce2527588d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture_App/issues/838#issuecomment-174821659>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by zkdzegede** [comment]
Yeah that would actually be the most ideal, to have control over the type of gauge I want to use.

Obviously a future feature but it would be nice if for instance suspension data was an gauge that looked like a a fork/shock and was connected to a motorcycle 3d model :-D

**Comment by brentpicasso** [comment]
Closing. Solution, create a virtual channel that is either 1 or 0 to indicate a boolean status. .

**Comment by zkdzegede** [comment]
👍
