### ISSUE TITLE
rcpapi.py:rc_detect_win can start unlimited duplicated threads

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture_App#846]
Every time the app detects a racecapture (For what ever reason) we call `.start` on several objects in that method.  That in turn will start multiple threads which do individual tasks.  This is great the first time we start up, but each successive time we detect a racecapture (for whatever reason) we will re-start a duplicate version of the same thread.  That will cause trouble and consume resources.  We either need to ensure those threads are destroyed when an RCP is no longer detected as "present" (ideal) or we need to ensure that we can't create duplicate instances of those threads once

**Comment by stieg** [comment]
Seems to actually only apply to `_status_pump` as `dataBusPump` has duplicate thread checks in its start method already.  Patch coming soon.

**Comment by brentpicasso** [comment]
Nice sleuthing. Can you target r/1.4.2 please for the PR and this issue?
thanks.

On Thu, Jan 28, 2016 at 8:17 PM, Andrew Stiegmann <notifications@github.com>
wrote:

> Seems to actually only apply to _status_pump as dataBusPump has duplicate
> thread checks in its start method already. Patch coming soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture_App/issues/846#issuecomment-176567206>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*
