### ISSUE TITLE
Occasional slow lap data loads in analysis view

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#854]
This is hard to reproduce consistently, but it does happen. Occasionally a lap or two takes a long time to load, sometimes over 10s. Usually after a fresh import.

[INFO   ] [Datastore   ] _query_channel_data function took 13464.0059471 ms
[INFO   ] [CachingAnalysisDatastore] querying 15_1 ['Distance', 'Speed']
[INFO   ] [Datastore   ] _query_channel_data function took 19.6471214294 ms
[INFO   ] [CachingAnalysisDatastore] querying 14_1 ['Distance', 'Speed']
[INFO   ] [Datastore   ] _query_channel_data function took 28836.1179829 ms

**Comment by ryandoherty** [comment]
Seeing this on master with a fresh sqlite db. Video https://www.youtube.com/watch?v=0YbQAlWWXO4&feature=youtu.be

**Comment by brentpicasso** [comment]
Kicking this forward.
