### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture_App#882]
Hit this issue on top of tree `commit 1a0827c4b0abf51ed74e9bdea3ecf7d1e3e36932` on my local machine.  RCP was re-connecting when it happened (or searching... don't know exactly).  App froze completely and it kept spewing this execption on the command line until I had to SIGKILL it.  Kivy 1.9.1.

```
[CRITICAL          ] [CrashHandler] Caught exception in Kivy loop: 'NoneType' object has no attribute '__getitem__'
[CRITICAL          ] [Traceback (most recent call last)]
  File "/usr/lib64/python2.7/site-packages/kivy/core/window/window_pygame.py", line 398, in mainloop
    self._mainloop()
  File "/usr/lib64/python2.7/site-packages/kivy/core/window/window_pygame.py", line 285, in _mainloop
    EventLoop.idle()
  File "/usr/lib64/python2.7/site-packages/kivy/base.py", line 333, in idle
    Builder.sync()
  File "/usr/lib64/python2.7/site-packages/kivy/lang.py", line 2082, in sync
    call_fn(next_args[:-1], None, None)
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by brentpicasso** [comment]
Try switching back to the asl specific 1.9.0 per instructions.  Certifying
1.9.1 is going to be a longer testing process than anticipated  .

Brent Picasso
Autosport Labs
Technology for Race and Street

**Comment by stieg** [comment]
:(.  I'll stick to 1.9.1 as this is very not common.  If it happens again Ill switch back

**Comment by brentpicasso** [comment]
Closing as no repro for current 1.9.0
