### ISSUE TITLE
Some GPS, Lap Timing data shown on dashboard even when it's switched off

### ISSUE THREAD

**Issue by kosenko-max** [autosportlabs/RaceCapture_App#884]
Hi.

In the app I switched off GPS, LapTimer and Accelerometer, but I still see some of them on dashboard. Since some of them disappeared - I guess it's a bug.
![screen shot 2016-02-09 at 16 26 27](https://cloud.githubusercontent.com/assets/468956/12911094/df42d1ec-cf4a-11e5-99b5-d4aa677bccd2.png)

**Comment by stieg** [comment]
Would seem like it?  What happens if you restart the app?  Did all the same channels re-appear?  May be related to internal meta-channels (calculations we do app side).

**Comment by brentpicasso** [comment]
Yes, this is an issue as these additional channels are virtual / computed channels generated by the app.  The app should not create these channels if the dependent channels are not present in the stream.

**Comment by brentpicasso** [comment]
resolved in 1.4.4
