### ISSUE TITLE
Add support for "state" key in Cell Net Status messages

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture_App#887]
As part of autosportlabs/RaceCapture-Pro_firmware/pull/416 there will be a new feature in the status message that provides a human readable string telling the user about the state of the cellular network.  It provides very useful message about your connectivity to the network (including informing you when the network is actively rejecting your SIM card).

This ticket tracks adding support for it in the app so it gets printed when present.

**Comment by stieg** [comment]
Oh yeah... the field is called "net_status" and lives in the "cell" object on the telemetry status message.

**Comment by ryandoherty** [comment]
We should document the status API messages somewhere. I think we have a GDoc.

**Comment by ryandoherty** [comment]
Or even better, put it on the wiki!

**Comment by stieg** [comment]
Wiki would be best.

On Wed, Feb 10, 2016 at 10:19 AM, Ryan Doherty <notifications@github.com>
wrote:

> Or even better, put it on the wiki!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture_App/issues/887#issuecomment-182454916>
> .
>



--
