### ISSUE TITLE
Start BT device search by the RaceCapture name

### ISSUE THREAD

**Issue by kosenko-max** [autosportlabs/RaceCapture_App#888]
Due to fix 
* Connect to the first RaceCapture device it can detect, regardless of the name provided
it's now going through all unrelated and disconnected devices. It would be nice if it can save 3.5 minutes time and try original name first...

**Comment by brentpicasso** [comment]
Thanks. Optimizing this would be helpful.  What we can do is:

1- first attempt; scan all names for the corrected RaceCapture device.
2- upon successful connection, save the last successful name in preferences 
3- upon app re-start, try connecting to the saved name first
4- if app cannot connect to the saved name, fall back to searching all the names.  (goto 1 above)

Also worth noting, this is only showing up in the beta, not production release. Back-story: This is to ultimately support allowing people to customize the racecapture bluetooth name.
