### ISSUE TITLE
Display-only channel smoothing

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#895]
For some channels users will want to see an averaged or smoothed value so their gauges don't change value every 100ms, making it hard to read. An option to show a 'smoothed' or 'averaged' value (over the past few seconds, will have to play with this to figure out what works well) would achieve this.

This is *not* the same as having RCP do the smoothing. For many applications a user would want the raw values logged for later analysis, but for live display an averaged value is needed.

**Comment by kosenko-max** [comment]
Looks same as #886

**Comment by ryandoherty** [comment]
Yup, it is. I knew we had a ticket open for it, my search-fu was weak.
