### ISSUE TITLE
Memory and GUI object leakage during Alerts usage for gauges

### ISSUE THREAD

**Issue by kosenko-max** [autosportlabs/RaceCapture_App#899]
On a Galaxy Tab with 2GB of RAM after half an hour dashboard usage it takes 700Mb of memory and whole GUI of application and system becomes completely unusable - gauges updating 1 times per second and becomes slower and slower, top bar of Android can't move, it's impossible to choose a channel because it treats any sliding movements as a click only. Kill and restart helps for some time until same thing happens again.

**Comment by brentpicasso** [comment]
thank you for the report. 

This is 1.4.3 beta android, correct?
Was it resting on any particular dashboard screen while this happened?  
Also, approximately how many total channels were being streamed to the app?

The app normally gets used in endurance racing by many users for multiple hours on end, so replicating your conditions is important.

If you can run a static test with a default configuration (no extra channels) and let it run overnight would be a good comparison.

**Comment by brentpicasso** [comment]
Currently testing 100 channels with this script. Lua reports after running:

lua: Completed updating LUA. Flashing... win!
lua: Initializing...
lua: Loading lua script (len = 360): SUCCESS!
lua: memory usage: 27KB








setTickRate(50)
vChannelCount = 100
vChannels = {}

for c=1,vChannelCount do
  local name='ch_' ..c
  local id = addChannel(name, 10, 0, 0, 100)
  table.insert(vChannels, {id, 0})
end

function onTick()
  for c=1, #vChannels do
    local v = vChannels[c][2]
    local id = vChannels[c][1]
    v = v + 1
    setChannel(id, v)
    vChannels[c][2] = v
  end
end

**Comment by kosenko-max** [comment]
On 7 March 2016 at 01:41, Brent Picasso <notifications@github.com> wrote:

> thank you for the report.
>
> This is 1.4.3 beta android, correct?
>
This is latest version from
https://play.google.com/store/apps/details?id=com.autosportlabs.racecapture

Not beta.

> Was it resting on any particular dashboard screen while this happened?
>
 It was resting on a 5 round gauges screen.

> Also, approximately how many total channels were being streamed to the app?
>
No GPS, no laptiming, no accelerometers, 7 analog channels, 1 RPM channel,
23 virtual channels from script in this state:
https://gist.github.com/kosenko-max/6eaf4f1fb47835435ec7


> The app normally gets used in endurance racing by many users for multiple
> hours on end, so replicating your conditions is important.
>
> If you can run a static test with a default configuration (no extra
> channels) and let it run overnight would be a good comparison.
>
I will try to do that. Initially I thought it's a Bluetooth congestion. So
I had it for quite a time happening before already. But later I found all
USB and additional BT devices turned off, tablet restarted, app restarted,
RCP restarted, but it happens again and again. And it takes too much *RAM
of tablet* and while you go to the home screen it works ok, but if you try
to open overlay of top notification panel - it doesn't comes out at all
after a lot of struggles. So I assume it makes too many GUI objects.

**Comment by brentpicasso** [comment]
Thank you, I'm running the test script I wrote above as a long term test, simultaneously on desktop I can monitor the memory usage easily, as well as android. 

If you can test with the above script it would be interesting to see if you get the same results.

**Comment by brentpicasso** [comment]
12 hours of testing on ubuntu yielded this memory info:

12 hours of testing on desktop. Unfortunately, tablet battery died despite  being plugged into a charger.

10:20 am
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND 
8829 brent     20   0 1000140  79204   6244 S   5.7  0.5   0:04.38 main.py                                                
8785 brent     20   0 1267472 151004  39808 R  15.3  0.9   0:13.50 main.py  

10:26 pm
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND 
8829 brent     20   0 1000140  79204   6244 S   6.7  0.5  41:34.44 main.py                                                                                                                                          
8785 brent     20   0 1274220 160408  39848 S  16.6  1.0  95:45.15 main.py (edite


Unfortunately tablet died despite being plugged into charger. Will re-test tablet with a shorter period after a re-charge.

**Comment by brentpicasso** [comment]
Tested the 25 virtual channel script on my samsung tab 10 for 45 minutes, with same performance as when app first started, so no apparent drop in performance. 

Worth noting, this is on the 1.4.4 pre-release, which is very similar to the 1.4.3 beta currently available. May want to test with the 1.4.3 beta. 

@kosenko-max  how many different android devices did you experience this on?

**Comment by brentpicasso** [comment]
2 hours and 45 minutes on the tablet, no visible degradation in performance. 

let me know what you find out with other devices and with using this test script. Thank you.

**Comment by kosenko-max** [comment]
Sorry, was too busy to test. Will do it soon.

**Comment by kosenko-max** [comment]
I have adjusted script to:
setTickRate(30)
vChannelCount = 30
vChannels = {}

for c=1,vChannelCount do
local name='ch_' ..c
local id = addChannel(name, 1000, 2, 0, 100, "un")
table.insert(vChannels, {id, 0})
end

function onTick()
for c=1, #vChannels do
local v = vChannels[c][2]
local id = vChannels[c][1]
v = v + 1
setChannel(id, v)
vChannels[c][2] = math.random()*100
end
end

And setup high and low warnings on each channel. On a screen with 5 gauges and 3 channels at the bottom in a few minutes speed of screen redraw decreased to 0.5 fps and keeps going down. While original speed was something like 20 fps.

**Comment by brentpicasso** [comment]
Thanks, will re-check with that.

How many different android devices does this reproduce on?

-Brent

On Fri, Mar 11, 2016 at 6:39 PM, Max <notifications@github.com> wrote:

> I have adjusted script to:
> setTickRate(30)
> vChannelCount = 30
> vChannels = {}
>
> for c=1,vChannelCount do
> local name='ch_' ..c
> local id = addChannel(name, 1000, 2, 0, 100, "un")
> table.insert(vChannels, {id, 0})
> end
>
> function onTick()
> for c=1, #vChannels do
> local v = vChannels[c][2]
> local id = vChannels[c][1]
> v = v + 1
> setChannel(id, v)
> vChannels[c][2] = math.random()*100
> end
> end
>
> And setup high and low warnings on each channel. On a screen with 5 gauges
> and 3 channels at the bottom in a few minutes speed of screen redraw
> decreased to 0.5 fps and keeps going down. While original speed was
> something like 20 fps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture_App/issues/899#issuecomment-195644583>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by kosenko-max** [comment]
With exactly same original script as you've proposed - gauges are not moving and I don't see any speed decrease after application restart. Without application restart same script was same 0.5fps slow.

**Comment by kosenko-max** [comment]
I will try to do same on Mac and Note4

**Comment by kosenko-max** [comment]
On Mac my script without warnings took 380Mb. Turning on warnings pushed memory to rapid growth (1Gb after 2 minutes) and whole system is barely usable (github comment symbols appearing after few seconds).

**Comment by brentpicasso** [comment]
Thanks. So when you say 'warnings' you mean colored alerts for the gauges?

**Comment by kosenko-max** [comment]
And I have 2015 Retina Mac  Pro with 8Gb and 4Gb of free memory without any CPU activity.  It's 100% eating GUI objects since I can't use whole system anymore and typing this comment with screen refresh every 10 seconds. Yes - colored alerts.

**Comment by kosenko-max** [comment]
After 5 minutes it took 1.5Gb of memory for python process. Killing of it immediately restored system to normal state. So it's non platform specific issue.

**Comment by brentpicasso** [comment]
Got it. I just reproduced the problem with alerts configured. It seems without alerts enabled it remains stable.  

Thank you, now we know where to focus.

**Comment by kosenko-max** [comment]
Thanks.

**Comment by kosenko-max** [comment]
And while you are there - middle gauge somehow uses same alert settings as top right one.

**Comment by kosenko-max** [comment]
And from bottom numeric line - right one has same alert settings as bottom right gauge.

**Comment by kosenko-max** [comment]
Ah, sorry, my bad - those were just same channels. Ignore last 2 messages

**Comment by kosenko-max** [comment]
I can confirm that alerts are the reason. Bottom line alerts have no effect, but gauges start leakage that is unrestorable - even after switching them off application doesn't return to normal state. Switching to configuration window and back is not releasing memory or GUI objects as well.

**Comment by brentpicasso** [comment]
Fix needs to be made in kivy 1.9.0 SVG renderer.

**Comment by brentpicasso** [comment]
Tracking issue in Kivy project: https://github.com/kivy/kivy/issues/4110

**Comment by brentpicasso** [comment]
@kosenko-max  this is now available in the beta 1.4.4 app in the android play store.  Announcement here: https://groups.google.com/forum/#!topic/autosportlabs-beta-testers/krFwAW08CZM

**Comment by kosenko-max** [comment]
Great. Thanks!
