### ISSUE TITLE
ver_bugfix causes error in app

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#906]
App Status screen should be tolerant of API values it does not recognize, for compatibility reasons.

From Sentry
-----

KeyError: 'ver_bugfix'
(35 additional frame(s) were not displayed)
...
  File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:12154)
  File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (kivy/_event.c:11451)
  File "home/brent/git-projects/RaceCapture_App/.buildozer/android/app/autosportlabs/racecapture/views/status/statusview.py", line 162, in _on_menu_select
  File "home/brent/git-projects/RaceCapture_App/.buildozer/android/app/autosportlabs/racecapture/views/status/statusview.py", line 183, in update
  File "home/brent/git-projects/RaceCapture_App/.buildozer/android/app/autosportlabs/racecapture/views/status/statusview.py", line 204, in render_system

**Comment by ryandoherty** [comment]
So the app is looking for `ver_bugfix`, but RCP 2.9.0 is returning `ver_bufix`:

https://github.com/autosportlabs/RaceCapture-Pro_firmware/commit/1bebacbfe7d46b94f3fcb3969d95c4cce4eced15#diff-10c943a99288610693831f7dfca4e479R245

@stieg Intentional?

**Comment by stieg** [comment]
Nope.  Not intentional.  Will fix.

On Wed, Mar 23, 2016 at 6:12 PM, Ryan Doherty <notifications@github.com>
wrote:

> So the app is looking for ver_bugfix, but RCP 2.9.0 is returning ver_bufix
> :
>
> autosportlabs/RaceCapture-Pro_firmware@1bebacb
> #diff-10c943a99288610693831f7dfca4e479R245
> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/commit/1bebacbfe7d46b94f3fcb3969d95c4cce4eced15#diff-10c943a99288610693831f7dfca4e479R245>
>
> @stieg <https://github.com/stieg> Intentional?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture_App/issues/906#issuecomment-200578211>
>



-- 
Autosport Labs
*Open Source Motor Sports*

**Comment by stieg** [comment]
Fixed by commit cdd94d57a886b304320900d5f9f4d63a0376f06a in r/2.9.0

On Wed, Mar 23, 2016 at 10:28 PM, Andrew Stiegmann <andrew@autosportlabs.com
> wrote:

> Nope.  Not intentional.  Will fix.
>
> On Wed, Mar 23, 2016 at 6:12 PM, Ryan Doherty <notifications@github.com>
> wrote:
>
>> So the app is looking for ver_bugfix, but RCP 2.9.0 is returning
>> ver_bufix:
>>
>> autosportlabs/RaceCapture-Pro_firmware@1bebacb
>> #diff-10c943a99288610693831f7dfca4e479R245
>> <https://github.com/autosportlabs/RaceCapture-Pro_firmware/commit/1bebacbfe7d46b94f3fcb3969d95c4cce4eced15#diff-10c943a99288610693831f7dfca4e479R245>
>>
>> @stieg <https://github.com/stieg> Intentional?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/autosportlabs/RaceCapture_App/issues/906#issuecomment-200578211>
>>
>
>
>
> --
> Autosport Labs
> *Open Source Motor Sports*
>
>


-- 
Autosport Labs
*Open Source Motor Sports*

**Comment by ryandoherty** [comment]
Thanks!
