### ISSUE TITLE
Speed up app

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#918]
This is a high-level task, but the app is slow for just about all tasks on my Nexus 6P, which ain't no slouch. We need to profile and optimize the app so it's responsive. Speed is a feature.

Here's a few key areas that I've noticed are slow. We should profile and benchmark first before making changes so we know we've made improvements.

UI/UX research says that a delay of 100ms or less from user interaction to response (click/type/tap => app response) is imperceptible and anything slower makes the computer feel slow. https://www.nngroup.com/articles/response-times-3-important-limits/
- [x] Speed up startup time
- [x] Speed up dashboard screens loading/swapping
- [x] Speed up scrolling when selecting channel to display for a gauge in the dashboard.
- [ ] Speed up scripting pane initial display/scroll

We also need to benchmark when RCP is connected/disconnected and running lots of channels.

**Comment by brentpicasso** [comment]
thanks for logging this, I was thinking about this as well. 

@ryandoherty  What is your app load time? My Samsung S5 Active loads in just under 5 seconds.

**Comment by ryandoherty** [comment]
On my Nexus 6P load time is ~4s to display more than the RC logo. Going from RC logo => usable app takes at least a few more seconds, depends on what screen is being loaded.

**Comment by ryandoherty** [comment]
Also to note that the app 'feels' slow is subjective, but when I say that what I mean is responsiveness to tapping/clicking on things or scrolling. Hard to quantify right now, but very important.

**Comment by brentpicasso** [comment]
Right. Like, when first-time switching to dashboard mode from home screen
it hangs before showing the screen. A more responsive approach would
involve more visual feedback while things are being built / loaded.

On Sat, Apr 2, 2016 at 1:23 PM, Ryan Doherty <notifications@github.com>
wrote:

> Also to note that the app 'feels' slow is subjective, but when I say that
> what I mean is responsiveness to tapping/clicking on things or scrolling.
> Hard to quantify right now, but very important.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture_App/issues/918#issuecomment-204800491>
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by brentpicasso** [comment]
Closing this - we have separate issues to cover the script editing window, no need to cover it here.
