### ISSUE TITLE
Non existent virtual channels in Select Channel on dashboard

### ISSUE THREAD

**Issue by kosenko-max** [autosportlabs/RaceCapture_App#926]
For some reason I have channels like tire temperature, ride height, Analog 1-8, all pwm. 80% of channels for dashboard channel selection are not existing and yet I see them in every list on the app. Especially confusing to see Analog 1 together with properly named channel on the same input.

Also rest of the channels are never alphabetically sorted and from start to start they change order in the drop downs and on the main dashboard.

**Comment by ryandoherty** [comment]
Can you provide app version, platform, hardware version and firmware version? And can you upload your configuration here? (Strip out your device id from the saved file). Thanks!

**Comment by brentpicasso** [comment]
Please confirm app version.  To clarify, the latest 1.4.x app will show all
channels before racecapture is connected , and after racecapture is
connected it will only show configured channels.  In both cases it will
order channels alphabetically.

**Comment by kosenko-max** [comment]
App is latest beta. Platform MK2. Firmware 2.8.7 and 2.9.0RC4. I can see those things in Analog channel select (actually I don't even understand a meaning of this drop down). Sometimes I see them in channel select on dashboard (not this time). I assume it has something to do with often timeouts of config reading that I have (except analog channel selector).

![screen shot 2016-04-10 at 18 51 16](https://cloud.githubusercontent.com/assets/468956/14409692/6d15d028-ff4d-11e5-9b0e-cbc236c16623.png)

**Comment by brentpicasso** [comment]
The configuration view is different than than dashboard channel selection view, by design.

When configuring the system a list of suggested canonical channel names are provided for users to select from when setting up their system.

**Comment by kosenko-max** [comment]
I see same list in the Select Channel from time to time after some bugs
with script updates.

If this is for reference - it's very confusing. I can choose Analog 5 on
Analog 3 channel - is it going to be reading now different channel there?
Or I can choose my digital named inputs in analog input. What would it mean?

Plus sometimes it changes precision and range which goes completely off. I
assume now it's some kind of helper library, but I see more confusion it
makes than value.

**Comment by brentpicasso** [comment]
Under the configuration screen:

the analog channel configuration the dropdown list is a list of suggested channel names for common channels. When one of these channels are selected, the min, max, precision and units values are updated to reflect typical good values for that type of channel.  

Example: FuelLevel
min: 0
max: 100
units: %
precision: 0

This list is a collection of official canonical channel definitions, and they're provided as a convenient list for common sensor types, so they are are consistent - e.g. EngineTemp, TPS, OilPress. 

When on the dashboard screen and a user selects a channel:

* If RCP is connected, only channels configured on RCP are shown. 
* If RCP is not connected, it falls-back to showing the generic list of system channels

From our testing, the system is behaving in the way described here, so this issue will be closed. Thanks!

**Comment by kosenko-max** [comment]
I double checked - connected RCP gives me all sample channels along with a
real ones and everything is unsorted on the dashboard channel selector.
Together with sluggish scrolling it takes me easily 2 minutes just to
change a channel.

**Comment by brentpicasso** [comment]
What version of the app did you observe this on?

**Comment by kosenko-max** [comment]
Sorry, my car at the shop far away. It is previous version before last
update as far as I remember. I will check next weekend specifically.

**Comment by brentpicasso** [comment]
Thanks. The updated behavior should be present in the 1.4.x app version and later (android beta). The 1.3.11 android app in production doesn't yet have this update.

**Comment by kosenko-max** [comment]
It's 100% 1.4.x

I assume it's erratic behavior - something pushing it to show all sample
channels in unsorted manner even though functionality is in place.
