### ISSUE TITLE
Asynchronous communication and storage access

### ISSUE THREAD

**Issue by kosenko-max** [autosportlabs/RaceCapture_App#929]
Part of the reason why App sometime very unresponsive is that it does communication job at the GUI thread. For example in this bug https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/506 when it tries to read a log and system is not responding - it hangs indefinitely without any sign. On Mac it's not even possible to kill it - even with Force Quit or restart going it's resisting any attempts to exit. 

But aside of those kind of critical cases - it's just not possible to do responsive GUI if anything that can have non predictable delay done on GUI thread - any communication, storage access and so on. Currently quite often it stucks or stutters on those events.

**Comment by brentpicasso** [comment]
Improvements to the RCP log viewer will appear in 1.4.6 release, resolves UI hanging issue with high volume log viewing updates.
