### ISSUE TITLE
iOS UI fixes

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#932]
Work needed to do for making the app on iOS look and behave correctly.

**Comment by ryandoherty** [comment]
Commit to fix ios keyboard height:
https://github.com/kivy/kivy/commit/40067a63808ec7554f82d49b87f68a776982a9d9

Need to create our own branch with that commit on to 1.9.1 and build it.

**Comment by brentpicasso** [comment]
1.12.0 has fixes to deal with iOS widget sizing and text spilling.
