### ISSUE TITLE
Add Configuration for WiFi to our Configuration Setup

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture_App#979]
Now that WiFi is nearing completion we need a way to configure it from within the app.  Here is what needs to be configured:

Wifi Client
* Enabled <bool>
* SSID <string - Max 24 chars currently>
* Password <string - Max 24 chars currently>

Wifi AP
* Enabled <bool>
* SSID <string - Max 24 chars currently>
* Password <string - Max 24 chars currently>
* Channel <Integer> 1 - 11 are the only valid options
* Encryption <String> - valid values are {none|wpa|wpa2|wpa/wpa2}.  "wep" is also valid, but is not supported by the ESP8266 device.

Here are some examples of the JSON strings:
* `{"set_wifi_client_cfg":{"active": true,"ssid":"fooworks","passwd":"barwasntgoodenough"}}`
* `{"set_wifi_ap_cfg":{"active": true,"ssid":"StiegRCP","passwd":"driveitlikeyoustoleit","channel":11,"encryption":"wpa2"}}`

If you pass in an invalid config, our API will return a -1 to indicate an invalid parameter.  Else it will return a 1 to indicate a successful action.

**Comment by ryandoherty** [comment]
Were these commands to be changed to match existing config commands? I thought I heard something about it. @stieg @brentpicasso

**Comment by stieg** [comment]
Sorry for the delay.  Yes @brentpicasso has asked that they be changed.  I also need to add support for completely disabling the WiFi device.  This is tracked at autosportlabs/RaceCapture-Pro_firmware#638

**Comment by ryandoherty** [comment]
I'm trying this command, but getting a -1 response with 2.10.0, looks valid to me @stieg , can you verify?

`{"setWifiCfg":{"active":true,"ap":{"active":false,"encryption":"","password":"","ssid":"","channel":1},"client":{"active":true,"password":"","ssid":"foobar"}}}`

**Comment by stieg** [comment]
Encryption is invalid ("" is invalid there).  You should instead just give it the following:
```json
{"setWifiCfg":{"active":true,"ap":{"active":false},"client":{"active":true,"password"<your password>","ssid":"foobar"}}}
```

**Comment by stieg** [comment]
See above note about valid values for encryption (If you specify it that is).

**Comment by brentpicasso** [comment]
Could you also specify null?

Brent Picasso
Autosport Labs
Technology for Race and Street

**Comment by stieg** [comment]
null is not a valid encryption value either.  That as part of the spec that
I proposed... got to be one of the said arguments or not provided at all.
What would 'null' mean on my end?

**Comment by ryandoherty** [comment]
Ok, I was thinking 'none' was a blank string. I can use none for now.
