### ISSUE TITLE
Direct CAN mapping configuration

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#982]
Enable configuration management for mapping CAN data to channels.  Provide an interface that allows defining how to extract data from a CAN message, transform it using a formula, and set it to a channel.

Each Mapping has the following configuration:
- A standard ChannelConfig:
- Name
- Units
- min
- max
- logging precision
- CAN Mapping
- Source data type(unsigned, signed, IEEE754)
- Endian
- CAN channel
- CAN ID
- Bit offset within CAN message
- bit width
- Value multiplier (float)
- Value offset (float)

Compliment issue in firmware:
https://github.com/autosportlabs/RaceCapture-Pro_firmware/issues/172

Work currently tracked in https://github.com/autosportlabs/RaceCapture_App/tree/p/brentpicasso/CAN_mapping

![image](https://cloud.githubusercontent.com/assets/3267533/15275613/25afb2be-1a85-11e6-9a71-be43a48b753b.png)

**Comment by kosenko-max** [comment]
Definition of sample rate in Hz looks confusing. If this is mapping of CAN messages without requests - what is the point of sample rate at all? If it is request-response based data then sample rate probably should be in form of priority (1 means request every cycle, 2 means every second cycle, etc).

For request-response based systems only 1 thing is needed in GUI - CAN request message as hex string. Such a pain to do CAN messaging in Lua - it doesn't fit into memory with the rest of the stuff no matter what I do.

**Comment by brentpicasso** [comment]
@kosenko-max the sample rate is how fast we internally sample the current value, independently of how fast the CAN messages are coming in.

Note, this is not for PID style request / replies, but for mapping streaming CAN messages.

**Comment by kosenko-max** [comment]
I understand it's not for it.

But honestly, I don't see much of the difference that it would require
separate GUI. In my particular case 1 request generates large multi-message
answer containing most of the log data. It requires work with different
byte modes and conversion of results by multiplier and offset. Request is
actually memory address and number of bytes to read from it and it's not a
PID. I don't see anything like that coming to OBD. But I can see how adding
request field makes all this a reality.

On Evo ECU - there is a possibility to tap into ECU harness and start
listening stream of CAN messages - it has same format of data as OBD.
Except it's not enough data.

If I had an option to do that in Lua - I would. But unfortunately it's 50kb
RAM.

**Comment by brentpicasso** [comment]
Thanks. We'll work to accommodate what you need into the system overall, using your current script as a guideline.
