### ISSUE TITLE
Ensure Our App Works with MK1

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture_App#994]
After the Vodden the Hell race 2016 it has become quite clear that there is a ton of confusion about what apps work with what versions of firmware and even if the App works with MK1 at all?  The latter is very important as many user who provide valuable feedback still have MK1 units (some of the original OGs of RaceCapture).  We need to ensure they have a good experience, which means that basic functionality **MUST WORK**.

This ticket tracks testing MK1 on the app and making the necessary adjustments on the app so that it does work.  If we choose to limit which app works with MK1, then this will track implementing some form of feature that directly informs customers of the situation and how to fix it.  Doing anything less than this will lead to a poor customer experience as both Ryan and I experienced this past weekend.

**Comment by brentpicasso** [comment]
1.8.0 works with MK1
